"""Setup utilities for Dav."""

from pathlib import Path

from rich.console import Console
from rich.panel import Panel
from rich.prompt import Prompt

console = Console()


def run_setup() -> None:
    """Run initial setup for Dav."""
    console.print(Panel.fit(
        "[bold green]Dav Setup[/bold green]",
        border_style="green"
    ))
    
    dav_dir = Path.home() / ".dav"
    env_file = dav_dir / ".env"
    
    # Create .dav directory
    console.print("\n[bold]Step 1:[/bold] Creating .dav directory...")
    try:
        dav_dir.mkdir(parents=True, exist_ok=True)
        console.print(f"[green]✓[/green] Created directory: {dav_dir}")
    except Exception as e:
        console.print(f"[red]✗[/red] Error creating directory: {e}")
        return
    
    # Check if .env already exists
    env_file_exists = env_file.exists()
    env_file_empty = False
    
    if env_file_exists:
        # Check if file is empty or only contains whitespace
        try:
            with open(env_file, "r") as f:
                content = f.read().strip()
                env_file_empty = len(content) == 0
        except Exception:
            env_file_empty = False
        
        if env_file_empty:
            console.print(f"\n[yellow]⚠[/yellow] Configuration file exists but is empty: {env_file}")
            console.print("[yellow]The file will be overwritten with new configuration.[/yellow]")
        else:
            console.print(f"\n[yellow]⚠[/yellow] Configuration file already exists: {env_file}")
            overwrite = Prompt.ask("Overwrite existing .env file?", choices=["y", "n"], default="n")
            if overwrite.lower() != "y":
                console.print("[yellow]Skipping .env file creation.[/yellow]")
                return
    
    # Ask for backend preference
    console.print("\n[bold]Step 2:[/bold] Configure API key")
    backend = Prompt.ask(
        "Which AI backend do you want to use?",
        choices=["openai", "anthropic", "gemini"],
        default="openai"
    )
    
    # Ask for API key (Gemini typically uses GEMINI_API_KEY / Google API key)
    api_label = "GEMINI/Google" if backend == "gemini" else backend.upper()
    api_key = Prompt.ask(
        f"Enter your {api_label} API key",
        password=True
    )
    
    if not api_key:
        console.print("[red]✗[/red] API key is required. Setup cancelled.")
        return
    
    # Create .env file
    console.print("\n[bold]Step 3:[/bold] Creating .env file...")
    
    if backend == "openai":
        env_content = f"""# Dav Configuration
# Generated by: dav --setup

# OpenAI Configuration
OPENAI_API_KEY={api_key}
DAV_BACKEND=openai
DAV_DEFAULT_MODEL=o4-mini
# DAV_OPENAI_MODEL=o4-mini  # Override default OpenAI model

# Optional: Anthropic Configuration (if you want to switch later or enable failover)
# ANTHROPIC_API_KEY=your_anthropic_api_key_here
# DAV_ANTHROPIC_MODEL=claude-sonnet-4-6

# Optional: Gemini Configuration (if you want to switch later or enable failover)
# GEMINI_API_KEY=your_gemini_api_key_here
# GOOGLE_API_KEY=your_google_api_key_here  # Alternative to GEMINI_API_KEY
# DAV_GEMINI_MODEL=gemini-2.5-pro

# Permissions
DAV_ALLOW_EXECUTE=false

# Sessions
DAV_SESSION_DIR=~/.dav/sessions

# Context Management (optional)
# DAV_MAX_STDIN_CHARS=32000  # Maximum stdin characters to capture
# DAV_MAX_CONTEXT_TOKENS=80000  # Maximum tokens for context window
# DAV_MAX_CONTEXT_MESSAGES=100  # Maximum messages to include in context

# Script Settings (optional)
# DAV_SCRIPTS_DIR=~/.dav/scripts      # Directory for generated scripts
"""
    elif backend == "anthropic":
        env_content = f"""# Dav Configuration
# Generated by: dav --setup

# Anthropic Configuration
ANTHROPIC_API_KEY={api_key}
DAV_BACKEND=anthropic
DAV_DEFAULT_MODEL=claude-sonnet-4-6
# DAV_ANTHROPIC_MODEL=claude-sonnet-4-6  # Override default Anthropic model

# Optional: OpenAI Configuration (if you want to switch later or enable failover)
# OPENAI_API_KEY=your_openai_api_key_here
# DAV_OPENAI_MODEL=o4-mini

# Optional: Gemini Configuration (if you want to switch later or enable failover)
# GEMINI_API_KEY=your_gemini_api_key_here
# GOOGLE_API_KEY=your_google_api_key_here  # Alternative to GEMINI_API_KEY
# DAV_GEMINI_MODEL=gemini-2.5-pro

# Permissions
DAV_ALLOW_EXECUTE=false

# Sessions
DAV_SESSION_DIR=~/.dav/sessions

# Context Management (optional)
# DAV_MAX_STDIN_CHARS=32000  # Maximum stdin characters to capture
# DAV_MAX_CONTEXT_TOKENS=80000  # Maximum tokens for context window
# DAV_MAX_CONTEXT_MESSAGES=100  # Maximum messages to include in context

# Script Settings (optional)
# DAV_SCRIPTS_DIR=~/.dav/scripts      # Directory for generated scripts
"""
    else:  # gemini
        env_content = f"""# Dav Configuration
# Generated by: dav --setup

# Gemini (Google AI) Configuration
GEMINI_API_KEY={api_key}
# Alternatively, you can use GOOGLE_API_KEY for compatibility with other tools
# GOOGLE_API_KEY={api_key}
DAV_BACKEND=gemini
DAV_DEFAULT_MODEL=gemini-2.5-pro
# DAV_GEMINI_MODEL=gemini-2.5-pro  # Override default Gemini model

# Optional: OpenAI Configuration (if you want to switch later or enable failover)
# OPENAI_API_KEY=your_openai_api_key_here
# DAV_OPENAI_MODEL=o4-mini

# Optional: Anthropic Configuration (if you want to switch later or enable failover)
# ANTHROPIC_API_KEY=your_anthropic_api_key_here
# DAV_ANTHROPIC_MODEL=claude-sonnet-4-6

# Permissions
DAV_ALLOW_EXECUTE=false

# Sessions
DAV_SESSION_DIR=~/.dav/sessions

# Context Management (optional)
# DAV_MAX_STDIN_CHARS=32000  # Maximum stdin characters to capture
# DAV_MAX_CONTEXT_TOKENS=80000  # Maximum tokens for context window
# DAV_MAX_CONTEXT_MESSAGES=100  # Maximum messages to include in context

# Script Settings (optional)
# DAV_SCRIPTS_DIR=~/.dav/scripts      # Directory for generated scripts
"""
    
    try:
        # Write the file
        with open(env_file, "w") as f:
            f.write(env_content)
        
        # Set secure permissions immediately after creation
        from dav.file_security import set_secure_permissions
        if set_secure_permissions(env_file):
            console.print(f"[green]✓[/green] Set secure permissions on configuration file")
        else:
            console.print(f"[yellow]⚠[/yellow] Warning: Could not set secure permissions on configuration file")
        
        # Verify the file was written correctly
        with open(env_file, "r") as f:
            written_content = f.read()
            if len(written_content.strip()) == 0:
                console.print(f"[red]✗[/red] Error: File was written but appears empty!")
                console.print("[yellow]This might be a permissions issue. Try creating the file manually.[/yellow]")
                return
            if api_key not in written_content:
                console.print(f"[yellow]⚠[/yellow] Warning: API key might not have been written correctly.")
                console.print("[yellow]Please verify the file contents manually.[/yellow]")
        
        console.print(f"[green]✓[/green] Created configuration file: {env_file}")
        console.print(f"[green]✓[/green] File size: {len(env_content)} bytes")
    except PermissionError as e:
        console.print(f"[red]✗[/red] Permission denied: Cannot write to {env_file}")
        console.print("[yellow]Try running with appropriate permissions or create the file manually.[/yellow]")
        return
    except Exception as e:
        console.print(f"[red]✗[/red] Error creating .env file: {e}")
        return
    
    # Success message
    console.print("\n[bold green]✓ Setup complete![/bold green]\n")
    _print_trust_summary_panels()
    console.print("You can now use Dav. Try running:")
    console.print("  [cyan]dav \"how do I check disk usage?\"[/cyan]\n")
    console.print("To edit your configuration later:")
    console.print(f"  [cyan]nano {env_file}[/cyan]\n")
    console.print(
        "[dim]Trust & data flows:[/dim] see [bold]docs/trust-and-data.md[/bold] in the Dav repository.\n"
    )


def _print_trust_summary_panels() -> None:
    """Short post-setup transparency (doc 08)."""
    from rich.panel import Panel

    console.print(
        Panel.fit(
            "[bold]What is sent to the AI provider[/bold]\n"
            "Your questions, session context (OS, paths, summary), and (when enabled) tool outputs—"
            "redaction is applied on many paths. API keys stay in ~/.dav/.env.",
            title="Privacy",
            border_style="dim",
        )
    )
    console.print(
        Panel.fit(
            "[bold]What stays local[/bold]\n"
            "Configuration under ~/.dav/, session files, audit log (default ~/.dav/logs/dav_audit.jsonl).",
            title="Local",
            border_style="dim",
        )
    )
    console.print(
        Panel.fit(
            "[bold]Next steps[/bold]\n"
            "Review docs/trust-and-data.md for full detail. Use --execute only when you intend "
            "to run shell or MCP tools; confirmations are on by default.",
            title="Safety",
            border_style="dim",
        )
    )
    console.print()


def run_root_installation() -> None:
    """Install Dav for root user."""
    from dav.update import detect_installation_method
    
    console.print(Panel.fit(
        "[bold yellow]Dav Root Installation[/bold yellow]",
        border_style="yellow"
    ))
    
    console.print("\n[yellow]⚠ Warning:[/yellow] Installing Dav for root user has security implications.")
    console.print("Root user has full system access. Only use this if you understand the risks.\n")
    
    response = Prompt.ask("Continue with root installation?", choices=["y", "n"], default="n")
    if response.lower() != "y":
        console.print("[yellow]Installation cancelled.[/yellow]")
        return
    
    # Detect installation method
    method = detect_installation_method()
    console.print(f"\n[bold]Detected installation method:[/bold] {method}\n")
    
    if method == "unknown":
        console.print("[yellow]⚠ Could not detect installation method.[/yellow]")
        console.print("Please install manually for root:")
        console.print("  [cyan]sudo pipx install git+https://github.com/poaxy/DAV.git[/cyan]")
        console.print("  or")
        console.print("  [cyan]sudo pip install git+https://github.com/poaxy/DAV.git[/cyan]")
        return
    
    # Get API key from current user or prompt
    current_env_file = Path.home() / ".dav" / ".env"
    api_key = None
    backend = "openai"
    
    if current_env_file.exists():
        try:
            from dotenv import load_dotenv
            import os
            load_dotenv(current_env_file)
            backend = os.getenv("DAV_BACKEND", "openai")
            if backend == "openai":
                api_key = os.getenv("OPENAI_API_KEY")
            elif backend == "anthropic":
                api_key = os.getenv("ANTHROPIC_API_KEY")
            elif backend == "gemini":
                # Prefer GEMINI_API_KEY but also support GOOGLE_API_KEY
                api_key = os.getenv("GEMINI_API_KEY") or os.getenv("GOOGLE_API_KEY")
        except Exception:
            pass
    
    if not api_key:
        console.print("\n[bold]Step 1:[/bold] Configure API key for root")
        backend = Prompt.ask(
            "Which AI backend do you want to use?",
            choices=["openai", "anthropic", "gemini"],
            default="openai"
        )
        api_label = "GEMINI/Google" if backend == "gemini" else backend.upper()
        api_key = Prompt.ask(
            f"Enter your {api_label} API key",
            password=True
        )
    
    if not api_key:
        console.print("[red]✗[/red] API key is required. Installation cancelled.")
        return
    
    # Install for root
    console.print("\n[bold]Step 2:[/bold] Installing Dav for root user...")
    
    import subprocess
    import sys
    
    try:
        if method == "pipx":
            # Install with pipx for root
            result = subprocess.run(
                ["sudo", "pipx", "install", "git+https://github.com/poaxy/DAV.git"],
                capture_output=True,
                text=True,
                timeout=300,
            )
        else:
            # Install with pip for root
            result = subprocess.run(
                ["sudo", sys.executable, "-m", "pip", "install", "git+https://github.com/poaxy/DAV.git"],
                capture_output=True,
                text=True,
                timeout=300,
            )
        
        if result.returncode != 0:
            console.print(f"[red]✗[/red] Installation failed: {result.stderr}")
            return
    except Exception as e:
        console.print(f"[red]✗[/red] Error during installation: {str(e)}")
        return
    
    # Set up root's .dav directory
    console.print("\n[bold]Step 3:[/bold] Setting up root's configuration...")
    
    root_dav_dir = Path("/root/.dav")
    root_env_file = root_dav_dir / ".env"
    
    try:
        root_dav_dir.mkdir(parents=True, exist_ok=True)
        
        # Create .env file for root
        if backend == "openai":
            env_content = f"""# Dav Configuration for root user
# Generated by: dav --install-for-root

# OpenAI Configuration
OPENAI_API_KEY={api_key}
DAV_BACKEND=openai
DAV_DEFAULT_MODEL=o4-mini
# DAV_OPENAI_MODEL=o4-mini  # Override default OpenAI model

# Optional: Anthropic Configuration (if you want to switch later or enable failover)
# ANTHROPIC_API_KEY=your_anthropic_api_key_here
# DAV_ANTHROPIC_MODEL=claude-sonnet-4-6

# Optional: Gemini Configuration (if you want to switch later or enable failover)
# GEMINI_API_KEY=your_gemini_api_key_here
# GOOGLE_API_KEY=your_google_api_key_here  # Alternative to GEMINI_API_KEY
# DAV_GEMINI_MODEL=gemini-2.5-pro

# Permissions
DAV_ALLOW_EXECUTE=false

# Sessions
DAV_SESSION_DIR=/root/.dav/sessions

# Context Management (optional)
# DAV_MAX_STDIN_CHARS=32000  # Maximum stdin characters to capture
# DAV_MAX_CONTEXT_TOKENS=80000  # Maximum tokens for context window
# DAV_MAX_CONTEXT_MESSAGES=100  # Maximum messages to include in context

# Script Settings (optional)
# DAV_SCRIPTS_DIR=/root/.dav/scripts      # Directory for generated scripts
"""
        elif backend == "anthropic":
            env_content = f"""# Dav Configuration for root user
# Generated by: dav --install-for-root

# Anthropic Configuration
ANTHROPIC_API_KEY={api_key}
DAV_BACKEND=anthropic
DAV_DEFAULT_MODEL=claude-sonnet-4-6
# DAV_ANTHROPIC_MODEL=claude-sonnet-4-6  # Override default Anthropic model

# Optional: OpenAI Configuration (if you want to switch later or enable failover)
# OPENAI_API_KEY=your_openai_api_key_here
# DAV_OPENAI_MODEL=o4-mini

# Optional: Gemini Configuration (if you want to switch later or enable failover)
# GEMINI_API_KEY=your_gemini_api_key_here
# GOOGLE_API_KEY=your_google_api_key_here  # Alternative to GEMINI_API_KEY
# DAV_GEMINI_MODEL=gemini-2.5-pro

# Permissions
DAV_ALLOW_EXECUTE=false

# Sessions
DAV_SESSION_DIR=/root/.dav/sessions

# Context Management (optional)
# DAV_MAX_STDIN_CHARS=32000  # Maximum stdin characters to capture
# DAV_MAX_CONTEXT_TOKENS=80000  # Maximum tokens for context window
# DAV_MAX_CONTEXT_MESSAGES=100  # Maximum messages to include in context

# Script Settings (optional)
# DAV_SCRIPTS_DIR=/root/.dav/scripts      # Directory for generated scripts
"""
        else:
            env_content = f"""# Dav Configuration for root user
# Generated by: dav --install-for-root

# Gemini (Google AI) Configuration
GEMINI_API_KEY={api_key}
# Alternatively, you can use GOOGLE_API_KEY for compatibility with other tools
# GOOGLE_API_KEY={api_key}
DAV_BACKEND=gemini
DAV_DEFAULT_MODEL=gemini-2.5-pro
# DAV_GEMINI_MODEL=gemini-2.5-pro  # Override default Gemini model

# Optional: OpenAI Configuration (if you want to switch later or enable failover)
# OPENAI_API_KEY=your_openai_api_key_here
# DAV_OPENAI_MODEL=o4-mini

# Optional: Anthropic Configuration (if you want to switch later or enable failover)
# ANTHROPIC_API_KEY=your_anthropic_api_key_here
# DAV_ANTHROPIC_MODEL=claude-sonnet-4-6

# Permissions
DAV_ALLOW_EXECUTE=false

# Sessions
DAV_SESSION_DIR=/root/.dav/sessions

# Context Management (optional)
# DAV_MAX_STDIN_CHARS=32000  # Maximum stdin characters to capture
# DAV_MAX_CONTEXT_TOKENS=80000  # Maximum tokens for context window
# DAV_MAX_CONTEXT_MESSAGES=100  # Maximum messages to include in context

# Script Settings (optional)
# DAV_SCRIPTS_DIR=/root/.dav/scripts      # Directory for generated scripts
"""
        
        # Write as root
        subprocess.run(
            ["sudo", "sh", "-c", f"cat > {root_env_file} << 'EOF'\n{env_content}\nEOF"],
            timeout=10,
        )
        
        # Set secure permissions on root's .env file
        subprocess.run(
            ["sudo", "chmod", "0600", str(root_env_file)],
            timeout=10,
        )
        
        console.print(f"[green]✓[/green] Root configuration created: {root_env_file}")
        console.print(f"[green]✓[/green] Set secure permissions on root configuration file")
        
    except Exception as e:
        console.print(f"[red]✗[/red] Error setting up root configuration: {str(e)}")
        return
    
    # Success message
    console.print("\n[bold green]✓ Root installation complete![/bold green]\n")
    console.print("You can now use Dav as root:")
    console.print("  [cyan]sudo dav --script \"write a script to update system packages\"[/cyan]\n")
    console.print("Or set up cron jobs as root with your generated scripts:")
    console.print("  [cyan]sudo crontab -e[/cyan]\n")
    console.print("[yellow]Security reminder:[/yellow] Root has full system access. Use with caution.")

